# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- none

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: Default
      demands:
       - agent.name -equals DESKTOP-ROG
    steps:
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'azure others registrycontainers'
        dockerComposeFile: '**/docker-compose-fe.yaml'
        action: 'Run a Docker Compose command'
        dockerComposeCommand: 'up --build --no-start'
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'azure others registrycontainers'
        dockerComposeFile: '**/docker-compose-fe.yaml'
        action: 'Push services'
     
