version: '3'
services:
  peregrine-mongo:
    container_name: peregrine-mongo-cont
    image: mongo:4.2
    ports:
      - 27017:27017
    volumes:
      - /data/db:/data/db

  zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  broker0:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper-1
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker0:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  peregrine-app:
    image: peregrine-app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - /data/springboot-docker-compose-app
    links:
      - mongo
    depends_on:
      - broker0
      - mongo

  peregrine-app-fe:
    image: peregrine-app-fe
    build:
      context: ./
      dockerfile: ./peregrineFE/Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - /data/springboot-docker-compose-app-fe
    depends_on:
      - peregrine-app
